# Data Representation {#bin}

Like many other examples we will come across, you can go very far in modern computing without knowing things that are vital to know in assembly. In this case it is binary or hexadecimal. Why is it that?

* The 6502 can do many operations (add, subtracting, moving things in memory) for which we don't need to understand binary, just hexadecimal. However, other operations we might like to do, such as multiplication and divide, are not things the 6502 can do natively. We need to create these functions ourselves (see Chapter \@ref(asm1)). For this we need to understand some intricacies of binary in order to perform the calculations.

* To understand generally how the 6502 operates it will be useful to be familiar with terms like bit, byte and nibble (see Chapter \@ref(sixty)). 

* A base 10 representation of numbers would be the ideal (in a human-readable sense, at least) way to deal with input and output. However, we will be required to use hexadecimal (though this does not mean we cannot convert it to base 10 later). So, to begin with at least, to understand our results, we will need to appreciate hexadecimal. 

Data is represented differently _internally_ and _externally_. The internal representation covers the program instructions themself, numeric data and finally alphanumeric data. The external representation (what we interact with as input and output) is represented as hexadecimal.   

## Internal Representations 

* A bit is a binary digit - a 0 or a 1

* 4 bits is a nibble, 8 is a byte

Microprocessors, like the 6502, store data internally as bytes. This data will need to be the program instructions and the data itself. The data will either be numeric or alphanumeric.

### Program Instructions

A program is essentially a list of instructions. These are stored as single or multiple bytes. The 6502 fetches bytes from memory. Therefore, a single byte instruction is faster than a multiple byte instruction. This is an important consideration when programming the 6502. The instructions the 6502 has will be discussed later.

### Numeric Data

To represent numeric data a numerous cases need to be taken care of. Firstly, we'll look at integers, which we'll represent with direct binary. Here, the right most bit represents 2^0^, the next one to the left is 2^1^, then 2^2^, and so on. The eights bits ($b$) of one byte will be represented as:

$$ b_{7}b_{6}b_{5}b_{4}b_{3}b_{2}b_{1}b_{0} $$

The powers of 2 are:

$$ 2^7 = 128,\;2^6 = 64,\;2^5 = 32,\;2^4 = 16,\;2^3 = 8,\;2^2 = 4,\;2^1 = 2,\;2^0 = 1 $$

So, a binary number, like ```0010 0011``` is:

$$ 
\begin{aligned}
 &  \quad b_{5} + b_{1} + b_{0} \\
 &  = 2^{5} + 2^{1} + 2^{0} \\
 &  = 32 + 2 + 1 \\
 &  = 35 
\end{aligned}
$$

You can go the other way to, from decimal to binary. Lets try 35 again:

$$
\begin{aligned}
& 35 \div 2 = 17 r 1 \rightarrow 1 \\
& 17 \div 2 =\enspace8 r 1 \rightarrow 1 \\
&\enspace8 \div 2 =\enspace4 r 0 \rightarrow 0 \\
&\enspace4 \div 2 =\enspace2 r 0 \rightarrow 0 \\
&\enspace2 \div 2 =\enspace1 r 0 \rightarrow 0 \\
&\enspace1 \div 2 =\enspace0 r 1 \rightarrow 1 \\
&\enspace0 \div 2 =\enspace0 r 0 \rightarrow 0 \\
&\enspace0 \div 2 =\enspace0 r 0 \rightarrow 0 \\
\end{aligned}
$$

This method give us a result of ```0010 0011```, which is what we'd expect.

Addition works as it would "normally". Single bits follow these rules:

$$
\begin{aligned}
& 0 + 0 = \quad\;0 \\
& 1 + 0 = \quad\;1 \\
& 0 + 1 = \quad\;1 \\
& 1 + 1 = (1)0 \\
\end{aligned}
$$

The $(1)$ represents a carry. Note, $10$ is the binary equivilent of 2. $2 + 1$ is done like:

$$
\begin{aligned}
& \enspace\; 10 \\
& \underline{+01} \\
& \enspace\; 11 \\
\end{aligned}
$$

The bits can "carry", like in normal integer addition. $3 + 1$ is:

$$
\begin{aligned}
& \enspace\; 0011 \\
& \underline{+0001} \\
& \enspace\; 0100 \\
\end{aligned}
$$

Our binary numbers can add correctly, and we can represent our integers correctly. However, there are two problems:

* We can only go up to 255 (if we only use 8 bits)
* We can only represent positive numbers

To solve the latter issue, we will introduce signed binary.

#### Signed Binary {-}

The left most bit is used for the sign. 

1 is: ```0000 0001``` while -1 is: ```1000 0001```

Immediatelly, we have reduced the magnitude from 255 to 127, oops. We can represent negative numbers now however. Lets try addition, $7$ and $-5$:

$$
\begin{aligned}
& \enspace\; 0000 0111 \\
& \underline{+1000 0101} \\
& \enspace\; 1000 1100 \\
\end{aligned}
$$

This is a problem, ```1000 1100``` is $-12$, which is clearly wrong. The solution to this is _two's complement_. To get to this point we will first have to introduce _one's complement_.

#### One and Two's Complement {-}

In **One's Complement** the positive number stays the same, ie, 1 is still```0000 0001```.
However, to get the negative we "swap" all the bits - all 0's become 1's and all 1's become 0's. This means -1 is: ```1111 1110```. As with signed binary, all positive numbers start with 0 and all negatives start with 1.

Lets try adding $-4$ and $+6$:

$$
\begin{aligned}
& \enspace\; 1111 1011 \\
& \underline{+0000 0110} \\
& \enspace\; 0000 0001 \\
\end{aligned}
$$

We have got a result of $1$, instead of $2$. We will have to expand one's complement before we get correct addition.

To arrive at **Two's Complement** you first make the transformation to One's Complement, then, for the negative number, add 1. So, 3 is: ```0000 0011``` while -3 is ```1111 1101```.

Lets try adding $-4$ and $6$ again:

$$
\begin{aligned}
& \enspace\; 1111 1100 \\
& \underline{+0000 0110} \\
& \enspace\; 0000 0010 \\
\end{aligned}
$$

Which gives us 2, so now, finally, everything Works! This is the representation of binary that will be used from now on. 

#### The Carry and the Overflow {-}

While adding/ subtracting numbers there are things to look for.

* If you add (unsigned binary) 128 (```1000 0000```) and (unsigned binary) 129 (```1000 0001```) is 257. The binary addition will result in ```(1) 0000 0001```. This extra, ninth bit, is the **Carry** bit. Our previous, two's complements, example of $-4$ and $6$ also includes a carry but this does not result in an incorrect result. This needs to be recognised and handled inside the processor. 

* Adding 64 (```0100 0000```) and 65 (```0100 0001```) results in ```1000 0001```, which is -127, and wrong. This is because of an internal carry from bit 6 to bit 7. When this bit change, that results in a sign change, occurs, this is what is called the **Overflow** bit.

The 6502 has flags in its architecture to keep track of the 2 scenarios.

### Alphanumeric Data

To represent Data we will use the ASCII encoding scheme. We will want to encode the 26 letters in both upper and lower case, plus 10 numbers, and then around 20 special symbols. This is all accomplished in 7 bits (which allows for 128 unique codes). The eighth bit can be used to verify that the contents of the byte has not been accidentally changed. This bit is called the _parity bit_. It is $1$ is there is an even number of bits set to $1$ and a $0$ is there is an odd number.

## External Representations

For the external representation of numeric data we can use hexadecimal. Here, digits are represented by the symbols $0$ to $9$, then $A$ to $F$. This range allows us to make the most of a nibble, using each combination to represent a symbol. Therefore, we can use a byte to hold 2 digits. So, $00$ = 0 and $FF$ = 255

## Conclusions {-}

We have see how data is represented interally and externally while using the 6502. This is not an exhaustive list though. Other forms of binary numbers, representations of alphanumeric data and external representation all exist in the form of BCD, EBCDIC and octadecimal, respectively. Discussion of these have been omitted as over time they have become irrelevent, it is beyond our scope or, in the case of BCD, many machines using 6502 turn the instructions related to it off.

[@zaks]
