# Addressing Techniques {#AdsTec}

When we talk about addressing, we are really asking "what is the source of data in our instructions"

## Addressing Modes

Addressing refers to specifying, inside the instruction, of the location of the operand on which the instruction will operate. There are numerous types of addressing modes, each specialising in a specific thing. The availabilitt of each mode is hardware specific as well, similar to the instruction classes we discussed in the previous chapter. Luckily, the 6502 has a diverse range of modes to choose from.

### Implicit Addressing

Instructions which operate on registers, usually, are _implicit_ instructions. These instructions do not explicitly contain the memory address they will operate on. Instead, these opcodes refer directly to the registers (eg, the accumulator). Since there are not many registers (usually <= 8) it will not require a lot of bits to encode these operations - a clear positive to these types of operations.

The 6502 has numerous opcodes that use _implicit_ addressing. These fall into two categories. The first are ones which operate on registers - these take only 2 clock cycles to finish and are:

<centre>

[CLC](#CLC), [CLD](#CLD), [CLI](#CLI), [CLV](#CLV), [DEX](#DEX), [DEY](#DEY), [INX](#INX), [INY](#INY), [NOP](#NOP), [SEC](#SEC), [SED](#SED), [SEI](#SEI), [TAX](#TAX), [TAY](#TAY), [TSX](#TSX), [TXA](#TXA), [TXS](#TXS), [TYA](#TYA)

</centre>

The other require memory access and take 3 clock cyles to work. These are: 

<centre>

[BRK](#BRK), [PHA](#PHA), [PHP](#PHP), [PLA](#PLA), [PLP](#PLP), [RTI](#RTI), 
[RTS](#RTS)

</centre>

### Immediate Addressing

Here, the instruction is made from the opcode followed by an 8, or 16, bit literal (ie, a constant). This is needed to load 8-bit values into 8-bit registers. Of course, if the hardware allows it the same can be done with 16-bit values. 

In the case of the 6502, the hardware limits us to using only 8-bit constants for immediate addressing. These instruction are therefore all 2 bytes in length - one for the opcode and one for the literal to be loaded or used in an arithmetic procedure. The instructions available are:

<centre>

[ADC](#ADC), [AND](#AND), [CMP](#CMP), [CPX](#CPX), [CPY](#CPY), [EOR](#EOR), [LDA](#LDA), [LDX](#LDX), [LDY](#LDY), [ORA](#ORA), [SBC](#SBC)

</centre>

### Absolute Addressing

This is the form of addressing more usually used to retrieve data from memory. In _absolute_ addressing the opcode is followed by a 16-bit address. A disadvantage here is that this will be a 3-byte instruction and hence a computationally expensive procedure. Other, more efficient, forms of addressing can sometimes be used to compensate for this

In the 6502, as expected, all absolute addressing instructions require 3 bytes. For all these instructions, except for JMP, they require 4 clock cycles. The opcodes available for this mode are:

<centre>

[ADC](#ADC), [AND](#AND), [ASL](#ASL), [BIT](#BIT), [CMP](#CMP), [CPX](#CPX), [CPY](#CPY), [DEC](#DEC), [EOR](#EOR), [INC](#INC), [JMP](#JMP), [JSR](#JSR), [LDA](#LDA), [LDX](#LDX), [LDY](#LDY), [LSR](#LSR), [ORA](#ORA), [ROL](#ROL), 
[ROR](#ROR), [SBC](#SBC), [STA](#STA), [STX](#STX), [STY](#STY)

</centre>

### Direct Addressing

With _direct_ addressing the opcode is followed by a 8-bit address. This provides an efficiency improvement over absolute addressing as it is only a 2-byte instruction. However we will be restricted to addresses between 0 and 255. This is called 0 page. Because of this, direct addressing is sometimes known as _zero-page_ addressing.

_Zero-page_ addressing requires 3 clock cycles. This is a significant speed up in comparison to absolute addressing and should therefore be used when possible. In the 6502, we will view the first 256 memory locations as working registers. This space, because of its inherit efficiency should be used to contain the most essential data that requires to be fetched at high speed. This will require careful memory management. The list of legal opcodes are: 

<centre>

[ADC](#ADC), [AND](#AND), [ASL](#ASL), [BIT](#BIT), [CMP](#CMP), [CPX](#CPX), [CPY](#CPY), [DEC](#DEC), [EOR](#EOR), [INC](#INC), [LDA](#LDA), [LDX](#LDX), [LDY](#LDY), [LSR](#LSR), [ORA](#ORA), [ROL](#ROL), [ROR](#ROR), [SBC](#SBC), [STA](#STA), [STX](#STX), [STY](#STY)

</centre>

### Relative Addressing

_Relative_ addressing is used primarily in jump or branch operations. In these, you would expect, it to be a 3-byte instruction - the opcode and a 16-bit address. However, we can reduce this to 2 bytes by only providing an 8-bit address which will displace us from our current position. This will allow us to move 128 locations forward or backword.

To differentiate this mode from the jump instruction we will refer to this as _Branches_. On the 6502 branches exclusively use the relative addressing mode whereas the jump instruction uses the absolute addressing mode. Timing (ie, number of clock cycles) for branches is something that should be considered carefully.

* If the test before the branch fails, and no branching needs to occur, this will take two clock cycles.
* If the test passes, a new memory address will need to be found and therefore the operation will take 3 cycles
* If the branching occurs, and the new memory address is found to be on the next page a carry or a borrow will be generated. This will result in the program taking 4 cycles. The movement from one page to another is something the hardware will deal with. However, some care must be taken depending on the context of when this will happen. For example, a loop where exact timing is important. 

In the 6502 the only instructions in this mode are the 8 branch instructions that test the flags. These are:

<centre>

[BCC](#BCC), [BCS](#BCS), [BEQ](#BEQ), [BMI](#BMI), [BNE](#BNE), [BPL](#BPL). [BVC](#BVC), [BVS](#BVS)

</centre>

### Indexed Addressing

_Indexed_ addressing is used to access multiple successive elements withing a block. The instruction is supplied with an opcode, an address and an index register. Here, the index register is used as a counter to access elements in the block. This is why we have numerous, specialised instructions to increment, decrement, and compare index registers against memory locations. There are two forms this can happen in:

* _absolute addressing_: Here, we use a 16 bit address and we are able to use register X or Y.
* _zero-page_: Here, we must use a 8 bit zero-page address, and are limited to using only register X (except for opcodes LDX and STX, which can also be modified by Y)

### Indirect Addressing

Many programs may want to be able to access a large block of memory. This block may grow or shrink dynamically, meaning keeping track of all the absolute addresses would be difficuly. Clearly, it is desirable to not keep this block stored at a fixed location. The solution is to keep the starting address of the block at a fixed location. Then, if you need access to this block you just need to access the one memory location to find where the block is. 

These instructions are an 8-bit opcode followed by an address. These instructions are simply used to retrieve a word from memory.

The 6502 does not provide a general way to do this. By that, it is meant that the address field is limited to 8 bits. In effect, this is a form of _zero-page_ addressing. The effective 16-bit address (the one that indicates the start of the block) is found by using the 8-bit zero-page address in the instruction. This is done in 2 steps. Firstly, the 8-bit address returns the least significant bit of the 16-bit target address. The other bit of the target address is found in the address that follows on from the one in the instruction. Furthermore, these instructions must be indexed. Indirect addressing can happen in 2 (and a half) ways.

#### _Pre-indexing_ (Indexed Indirect) {-}
Here, the 16-bit address is found, the contents of X are added, then this value is dereferenced and used as the "true" target address.

```
    LDX   #$01
    LDA   #$05
    STA   $01
    LDA   #$07
    STA   $02
    LDA   ($00,X)
```

Indexed Indirect can seem like a strange method. The X register is loaded with ```#$01```, ```$01``` is loaded with ```#$05``` and ```$02``` is loaded with ```#$07```. The final line (```LDA   ($00,X)```) is the confusing one. X is added onto ```$00```, giving us ```$01```. Then, the contents of ```$01``` and ```$02``` are loaded to give the final answer, which is the true target address, is: ```$0705```.


#### _Post-indexing_ (Indirect Indexed) {-}
In this scenario the 16-bit address is found and dereferenced, then the contents of the Y register are added. This is what is used as the "true" target address. Here is an example:

```
    LDY   #$01  
    LDA   #$03
    STA   $01
    LDA   #$07
    STA   $02
    LDA   ($01),Y
```

Lets follow this through, and find the result. Index register Y is stored with ```#$01```, then ```$01``` is loaded with ```#$03``` and ```$02``` is loaded with ```#$07```. The final line, ```LDA   ($01),Y```, will load ```$01``` and ```$02```, returning the address ```#0703```, which we will add the contents of Y onto. This gives the final answer, and true target address, ```#0704```.

#### An Exception to all the Rules

There is one important exception to all these rules that we must discuss before continuing, which is:

<centre>

[JMP](#JMP)

</centre>

The Jump command uses an absolute address to do indirect addressing, and requires no indexing. The address in the instruction contains the least significant bit of the 16-bit target address. The other bit of the target address is found in the address that follows on from the one in the instruction.

```
    LDA   #$01
    STA   $f0
    LDA   #$FF
    STA   $f1
    JMP   ($00f0)   ;dereferences to $FF01
```
Here, ```#$01``` is loaded into ```$f0```, and ```#$FF``` is loaded into ```$f1```. Then a jump takes us to ```$00f0```. The result, and target address, will therefore the ```$FF01```.

### Combinations

## Using the 6502 Modes

### Long and Short Addressing

### Indexing for Sequential Block Access

### Block Transfer (<256 elements)

### Block Transfer (>256 elements)

### Adding Two Blocks

### Largest Value

```
  LDA #$05 ; these 4 lines put $0205 into p0
  STA $01
  LDA #$02
  STA $02

  LDY #05
lowList:     ; deal with 5 to 1
  TYA
  STA ($01),Y
  DEY
  BNE lowList

  LDX #15
  LDY #05
highList:     ; deal with 15 to 11
  TXA
  INY
  STA ($01),Y
  DEX
  CPX #10
  BCS highList ; if X > 10, loop

  LDY #10   ; reload Y
  LDA ($01),Y   ; Assume last is biggest
loop:
  CMP ($01), Y  ; compare with next
  BCS smaller
bigger:
  LDA ($01), Y  ; Bigger (or same) replace best
smaller:
  DEY  ; Reached the first?
  BPL loop
  STA $0220
  RTS  ; Done
```

## Conclusions

* confusing. But, most microprocessors give you much less options. 
