# (PART) Input/ Output {-}

# Introduction to I/O {#io}

So, you probs want to be able to talk to devices, but how? Read on, and learn.

## Basics

To communicate with the outside world, and receive communication back, we will need to learn how to create, and receive, signals and pulses. To deal with these correctly we will also need to cover how properly enforce timings in our programs. 

### Signals

The simplest example of a signal is turning a device on or off. This can be done by manipulating an appropriating bit from a ```0``` to a ```1```. If the address of the device is stored in ```OUT1``` we can affect it like this:

```
TURNON  LDA $%00000001
        STA OUT1
```

Assuming the power control bit is the 0 bit, this would turn the relay on. However, this would also change all other bits in the register. A simple change to the program will fix this:

```
TURNON  LDA OUT1
        ORA $%00000001
        STA OUT1
```

The inclusive OR (ORA) will change only bit 1 here, and leave the rest intact.

To generate a pulse we would need to change the bit, then at a later point change it back. However, to do this we have to be able to accurately track the length of this delay.

### Delays

Delays can be generated by either software or hardware. Lets begin with the software side. Software delays are accomplished by counting. This is done by loading a register with a value and decrementing till we hit zero. Knowing the speed of the 6502 instruction set we can then accurately make delays of certain lengths.

```
DELAY   LDY   #07
NEXT    DEY   
        BNE   NEXT
```

The above code loads the integer ```7``` into Y then loops until it is decremented to zero. Then, it will move on. Lets look at how long these instructions take:

* LDY: 2 cycles
* DEY: 2 cycles
* BNE: 3 cycles (2 if no branch occurs)
* If a page boundary is crossed, 1 extra cycle

The LDY instruction will occur once, and the loop happens 7 times, with one of the BNE instructions only costing 2 cycles. So, the delay is calculated by: 

$$
\begin{aligned}
& 2 + 5 \times 7 = 36  
\end{aligned}
$$

The delay can be increased by loading a larger value into Y (up to 255). Or, you could make use of NOP - this does nothing for 2 cycles. 

For even longer delays, we would need to use 2 counters. Here, when the first counter reached zero, the second would be decremented by 1 and the first counter would be filled again. When the second counter gets to zero, the program terminates. However, this will result in the microprocessor doing nothing for potentially seconds. This can be acceptable in some situations, by may be a waste if other tasks could be being performed. Because of this, long delays are not usually dealt with by software, but rather by hardware. In some situations, if we need to guarentee accurace in the delay, even short delays may be done by hardware.

Hardware delays are implemented by programmable interval timers. The timer's register is loaded with a value and this is automatically decremented over time. When it is finished it will send an interupt to the program (interupts will be explained soon!).

### Sensing Pulses 

The opposite problem to creating pulses of a accurate length is sensing them. However, this includes an added problem. The programmer has control over generating a pulse, but has no control over when one may be recieved. We therefore must be always ready to detect one. This is done by _polling_ and _interupts_.

Polling is when the program watches and test a value in a certain register. When we recieve a pulse, this value we are watching will change. 

```
POLL    LDA   #$01
AGAIN   BIT   INPUT
        BEQ   AGAIN
ON      ......
```

The above example monitors bit 0 until it takes the value of 1. When this happens the program will break out of the loop and continue. A small modification will allow us to poll for a zero rather than a one:

```
POLL    LDA   #$01
AGAIN   BIT   INPUT
        BNE   AGAIN
ON      ......
```

Counting the duration of a pulse is done in a similar way to the previous examples. A counter will be incremented as long as the pulse exists. This counter will then be used to find the duration. For example:

```
DURTN   LDX   #0
        LDA   #$01
AGAIN   BIT   INPUT
        BEQ   AGAIN ; break out when pulse is detected (1)
LONGER  INX
        BIT INPUT
        BNE LONGER ; break out when pulse goes away (0)
```

The code detects a pulse, as before, then enters a second loop. Here, it increments X and when the pulse ends the loop can be broken out off. However, if X were to increase above 255 it would overflow. To count above that we would need to modify the program.

## Bit Transfer

We have looked at how we can look for, and create, pulses. Now, we can move on and look at how we can receive data after this is done. We have two options for this: parallel bit transfer and serial bit transfer.

### Parallel Bit Transfer

Here, we assume 8 bits of data needing transferred all exist at the address INPUT. So, it will be assumed that when a certain status word is valid, the data has been assembled at INPUT and is ready to be read. For simplicity, we will assume the number of words needing to be read is known. Here is code to do that:

```
PARAL   LDX   COUNT   ; our counter
WATCH   LDA   STATUS  ; load out status
        BPL   WATCH   ; are we ready to read the input?
        LDA   INPUT   ; if yes - load it!
        PHA           ; send to stack
        DEX           ; dec counter
        BNE   WATCH   ; if more words are gonna come, start loop again

```

Some notes:

* We have assumed we know the number of words to read. This may not be the case. If it was not, we could test to check for the presence of a _break-out character_, indicating the transmission has ended.
* We need to be mindful of the size of our stack. If we are transmitting more words than available stack space we can cause an overflow. To avoid this we could store to a specific memory location.

### Serial Bit Transfer

A more complex case is serial bit transfer. Here, the information will come in one at a time. This can be in either regular intervals (_synchronous transfers_), or in bursts (_asynchronous transfers_). We need to be able to account for both. 

Our program will watch the status of an input and when detected read it in. Unlike before, we will be storing it in an input register. When 8 bits have assembled it will be preserved in memory and the process can begin again. Again, we will assume we know the amount of data coming in. 

```
SERIAL    LDA   #$00
          STA   WORD
LOOP      LDA   INPUT
          BPL   LOOP
          LSR   A     ; if data is ready, bit from A to C
          ROL   WORD  ; shift from C to memory
          BCC   LOOP  ; continue if C=0
          LDA   WORD  
          PHA         ; load assembled word from A to stack
          LDA   #$01  ; reset bit counter
          STA   WORD
          DEC   COUNT
          BNE   LOOP  ; if more words to come, start again
```

We assume the following things:

* COUNT contains the number of incoming words
* WORD is the memory location we want to store the 8 incoming bits at
* INPUT is the input register. Bit 7 will contain the status. Bit 0 will contain the data.
* The first bit of incoming data will be a ```1```, which indicates data will follow.

This program is quite complex, so we can go through it in chunks. 

The first four lines are very similar to our previous programs - they check the status of the incoming data.

```
          LSR   A     ; if data is ready, bit from A to C
          ROL   WORD  ; shift from C to memory
          BCC   LOOP  ; continue if C=0
```

The above chuck, the "second" part of the code, handles what to do if the input is valid. The bits are now stored in the accumulator. The first line now shifts the content of the accumulator right one bit. This will cause bit 0, the bit containing the relevent data to fall into the carry bit. The ROL command cause the carry bit to fall into the right-most position of WORD but also cause the contents of the left-most position of WORD to fall into the carry. WORD will now contain ```0000 0001``` and C will contain ```0```. Finally, as long as the carry contains a zero, the loop will continue. If not, and the carry contains a ```1```, it means we have recovered 8 bits and we can break out. This can then be pushed to the stack, which is exactly what happens in the next two lines:

```
          LDA   WORD  
          PHA         ; load assembled word from A to stack
```

Lets continue to the last four lines:

```
          LDA   #$01  ; reset bit counter
          STA   WORD
          DEC   COUNT
          BNE   LOOP  ; if more words to come, start again
```

Now that we have assembled the first bit, there is no longer a guarentee the next bit we see will be a ```1```. The first two lines will correct this by sending ```0000 0001``` to the accumulator. Then, we decrement the counter and, if applicable, loop around.


This code has numerous interesting things to consider:

* We have an inbuilt way, by using the LSR and ROL instructions and tracking a ```1```, to tell if we have incoming data. If we did not do this we would have to use (potentially waste?) a register to count. 
* Bit 7 and 0 are good choices, as they allowing for easy testing and shifting.
* Still, we are pushing to the stack. What if we need more memory? It might be better to store to a memory address.
* We are assuming that the first bit will be a ```1```. What if it is not?
* Using the BIT instruction, we can test and transfer bits and not effect the accumulator. This would mean A could be used to store incoming bits.

Lets rewrite the code to account for these issues:

```
          LDX   #0
START     LDA   #$01    ; this will ensure the first bit is always 1
LOOP      BIT   INPUT   ; BIT will transfer bit 7 to the sign flag
          BPL   LOOP    ; test contents of sign flag
          LSR   INPUT   ; if data is ready, input bit 0 to C
          ROL   A       ; shift from C to A
          BCC   LOOP    ; continue if C=0
          STA   BASE,X  ; send A to memory location base,x 
          INX       
          DEC   COUNT
          BNE   START   ; if more words to come, start again
```

## Conclusions

We have looked at the basic structure of I/O communication. We've seen how to send and receive pulses and deal with delays. Once it is possible to detect these we have seen a range of options when it comes to how to receive data, both synchronously and asynchronously. The next thing to deal with is how to communicate with devices.




